[package]
name = "viacep"
version = "0.1.0"
authors = ["hermano <srhermanodecastro@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.18"
anyhow = "1"
serde = "1"
serde_derive = "1"
